language: ruby
rvm:
  - ruby-1.9.3-p484

before_script:
  - sudo apt-get install php5-cli

notifications:
  email: false

cache:
  - bundler

addons:
  code_climate:
    repo_token: d388156debf9e8c47dc04bd00e0edeefb7d3b9b3c1506304359271d9efe1f714

script: "bundle exec rspec --format progress"
